Adding fix for discord.py v2
Devoxin/Lavalink.py pull request #113
Opened 2021-08-19 13:10 UTC by AlexFlipnote

### Checks and guidelines:

* [x] Have you checked that there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked that only **single quotes** are used in the code, apart from the doc-strings?
* [x] Have you run a lint program on your code prior to submission?
* [x] Have you checked if `python run_tests.py` returns no errors?

Tests output: [link](https://hastebin.com/wuxitijohe.py) 

### Type of change

* [ ] Bug fix
* [x] New feature
* [ ] Improvement
* [ ] Breaking change
* [ ] This change is a documentation update

### Describe the changes:
- I've added a new cog example that fixes discord.py v2 issues.

2021-09-07 23:52 UTC, Hype3808 requested changes

2021-09-28 15:37 UTC, Soheab commented on examples/socket_fix_v2.py
> +        msg = discord.utils.from_json(msg)
`.from_json` was renamed to `._from_json`

2021-09-29 05:48 UTC, Hype3808 commented on examples/socket_fix_v2.py
> +        msg = discord.utils.from_json(msg)
oh ok

2021-10-02 14:40 UTC, Devoxin commented
I've merged #116 instead as it offers a newer, cleaner implementation

2021-10-02 14:40 UTC, closed without merging